---
title: "Pwani University, Introduction to R Workshop (2024)"
subtitle: "July 8th – 12th"
format: docx
editor: visual
---

# About the workshop

In this workshop, you will be introduced to the R and RStudio data analysis platforms. R is a simple programming language that enables the effective handling of data while providing excellent graphical support. R studio is a tool that provides a user-friendly environment for working with R. The course gives an overview of the basics of R and RStudio. The practical sessions will cover reading/importing data into the R environment, accessing and installing R packages, and writing annotated R code for data manipulation, analysis, and making graphical plots.

### Course prerequisites:

-   Basic statistics: Took an introductory statistics course at the undergraduate level.
-   Basic computing knowledge, such as, installing and uninstalling software.

### Computing requirements:

-   A laptop with at least 8GB RAM. .
-   Participants will download R and RStudio into their personal machines.
-   Instructions of how to download R and RStudio are given below.

### Download R:

-   Go to the R download site: https://cran.r-project.org/
-   Click on the link, which matches your operating system.
-   Download the current base version of R (R 4.4.1).
-   When you run the executable file, accept the default setting, (click next throughout).
-   Once you are done, you have R on your machine (look out for a blue R).

### Download RStudio:

-   Go to https://posit.co/download/rstudio-desktop/ and download R-Studio for Desktop.
-   Follow the prompts for your operating system (Mac/Windows).
-   Once you finish your download, the icon for R studio is a white “R” in a blue circle.

# Course Outline:

-   Day 1: Background, Getting Started, and fundamentals of R programming

    -   Installing R and RStudio
    -   Introduction to R and RStudio
    -   Fundamentals of Data Management (e,g, folder structure, R working directory)
    -   Good coding practices
    -   Data types (vectors, arrays, lists, data frames, and strings)
    -   R as a scientific calculator

-   Day 2: Data manipulation with Tidyverse

    -   Creating new variables
    -   Subset of data
    -   Data summaries
    -   Reading data into R
    -   Exporting data from R

-   Day 3: Numerical Exploration and introduction to data visualization

    -   Measures of central tendancy
    -   Measures of variability
    -   Introduction to plotting with R

-   Day 4: Data visualization with ggplot

    -   The Grammar of Graphics
    -   Data visualization with ggplot

-   Day 5: Exploratory data analysis

    -   Exploratory analysis of continuous data
    -   Exploratory analysis of categorical data
    -   Reproducible Research in R and wrap up.
